#!/bin/bash

clear && clear

make -s

if [ $? -ne 0 ]; then make clean && exit 1; fi

declare -a arr=("ls"
                "who | fgrep -i .edu > foo"
                "echo "xxx" > bar"
                "sort < foo|uniq -c >>bar #somthing??&"
                ">input ls"
                "<input>output cat"
                "echo \< \>\|\|\n"
                "cat bar"
                "cat foo"
                "cat input"
                "cat output"
                "mkdir temp_dir"
                "echo xx > temp_dir/zz"
                "cd temp_dir"
                "pwd"
                "ls"
                "cd .."
                "rm -rf temp_dir"
                "rm bar #some comments"
                "rm foo # >> something"
                "rm input output #"
                "ls")

file="/tmp/ffffff"

for i in "${arr[@]}"
do
  echo $i >> $file
done

/bin/bash $file > out1
valgrind --leak-check=full nsh $file > out2

diff out1 out2

rm $file

make -s clean
