#!/bin/bash

clear && clear

make -s

if [ $? -ne 0 ]; then make clean && exit 1; fi

declare -a arr=("ls"
                "who | fgrep -i .edu > foo"
                "echo "xxx" > bar"
                "sort < foo|uniq -c >>bar #somthing??&"
                ">input ls"
                "<input>output cat"
                "cat bar"
                "cat foo"
                "cat input"
                "cat output"
                "rm bar #some comments"
                "rm foo # >> something"
                "rm input output #"
                "ls")

file="/tmp/ffffff"

for i in "${arr[@]}"
do
  echo $i >> $file
done

/bin/bash $file > out1
nsh $file > out2

diff out1 out2

rm $file

make -s clean
